server:
  port: 8771
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: product-service
#  # 指定从那个配置中心读取
  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true
      profile: test

