server:
  port: 8776

spring:
  rabbitmq:
    host: 47.107.176.98
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 环境
env: bus2019
branch: master